### PR TITLE
Fix deposit partially

### LINKED ISSUE #92: Fix finalise deposits

### LINKED ISSUE #97: Persist commitments to DB to create MP's for deposits

### PR DESCRIPTION
**Pull request by vaibhavchellani**
Fixes #97

### CODE REVIEW

File: listener/processors.go [hunk 1]
```diff
@@ -374,24 +401,24 @@ func (s *Syncer) decompressMassMigrations(decompressedTxs [][]byte, meta [][4]*b
...
 	calldata, err := s.loadedBazooka.ParseCalldata(txHash, batchType)
 	if err != nil {
 		if err != bazooka.ErrNoTxs {
 			fmt.Println("unable to parse calldata")
-			return newRoot, err
+			return newRoot, commitments, err
 		}
-		return newRoot, nil
+		return newRoot, commitments, nil
 	}
```
Comment (ChihChengLiang) [inline listener/processors.go:412]: What do you think 

```
if err != bazooka.ErrNoTxs {
        return newRoot, commitments, nil
}
if err != nil {
        return newRoot, commitments, fmt.Errorf("unable to parse calldata %s", f)
}
```

**Review by ChihChengLiang — APPROVED** [review]
Great abstraction! 
Left a small nitpick
